#  Contains general info for data reduction
#  including directories, headers, and such.

###  Directories to find data ###
DATA_DIR = "../data/"
DATA_FILE = 'reduced_data.csv'

###  Headers of raw data taken from online pdf ###
HEADERS = {
    "Acquisition": [
        "id",
        "channel",
        "seller",
        "interest_rate",
        "balance",
        "loan_term",
        "origination_date",
        "first_payment_date",
        "ltv",
        "cltv",
        "borrower_count",
        "dti",
        "borrower_credit_score",
        "first_time_homebuyer",
        "loan_purpose",
        "property_type",
        "unit_num",
        "occupancy_status",
        "property_state",
        "zip",
        "insurance_percentage",
        "product_type",
        "co_borrower_credit_score",
        "insurance_type",
        "relocation_indicator",

    ],
    "Performance": [
        "id",
        "reporting_period",
        "servicer_name",
        "interest_rate",
        "balance",
        "loan_age",
        "months_to_maturity",
        "adjusted_months_to_maturity",
        "maturity_date",
        "msa",
        "delinquency_status",
        "modification_flag",
        "zero_balance_code",
        "zero_balance_date",
        "last_paid_installment_date",
        "foreclosure_date",
        "disposition_date",
        "foreclosure_costs",
        "property_repair_costs",
        "recovery_costs",
        "misc_costs",
        "tax_costs",
        "sale_proceeds",
        "credit_enhancement_proceeds",
        "repurchase_proceeds",
        "other_foreclosure_proceeds",
        "non_interest_bearing_balance",
        "principal_forgiveness_balance",
        "repurchase_make_whole",
        "foreclosure_write_off",
        "servicing_activity"
    ]
}

SELECT = {
    "Acquisition": [
        "id",
        "channel",
        "seller",
        "interest_rate",
        "balance",
        "loan_term",
        "origination_date",
        "first_payment_date",
        "ltv",
        "cltv",
        "borrower_count",
        "dti",
        "borrower_credit_score",
        "first_time_homebuyer",
        "loan_purpose",
        "property_type",
        "unit_num",
        "occupancy_status",
        "property_state",
        "zip",
        "insurance_percentage",
        "product_type",
        "co_borrower_credit_score",
        "insurance_type",
        "relocation_indicator"
    ],
    "Performance": [
            "id",
            "foreclosure_date",
            "recovery_costs"
    ]
}
FACTORS = { "In": [
        "id",
        "interest_rate",
        "balance",
        "loan_term",
        "origination_date",
        'acquisition_date',
        "ltv",
        "cltv",
        "borrower_count",
        "dti",
        "borrower_credit_score",
        "first_time_homebuyer",
        "occupancy_status",
        "property_state",
        "zip",
        "insurance_percentage",
        "co_borrower_credit_score"],
    "Final": [
            "id",
            "interest_rate",
            "balance",
            "borrower_count",
            "dti",
            "borrower_credit_score",
            "first_time_homebuyer",
            "zip",
            "foreclosure"
    ]
}
STATES_TO_VAL = {
    'AL' : 1,
    'AK' : 2,
    'AS' : 3,
    'AZ' : 4,
    'AR' : 5,
    'CA' : 6,
    'CO' : 7,
    'CT' : 8,
    'DE' : 9,
    'DC' : 10,
    'FM' : 11,
    'FL' : 12,
    'GA' : 13,
    'GU' : 14,
    'HI' : 15,
    'ID' : 16,
    'IL' : 17,
    'IN' : 18,
    'IA' : 19,
    'KS' : 20,
    'KY' : 21,
    'LA' : 22,
    'ME' : 23,
    'MH' : 24,
    'MD' : 25,
    'MA' : 26,
    'MI' : 27,
    'MN' : 28,
    'MS' : 29,
    'MO' : 30,
    'MT' : 31,
    'NE' : 32,
    'NV' : 33,
    'NH' : 34,
    'NJ' : 35,
    'NM' : 36,
    'NY' : 37,
    'NC' : 38,
    'ND' : 39,
    'MP' : 40,
    'OH' : 41,
    'OK' : 42,
    'OR' : 43,
    'PW' : 44,
    'PA' : 45,
    'PR' : 46,
    'RI' : 47,
    'SC' : 48,
    'SD' : 49,
    'TN' : 50,
    'TX' : 51,
    'UT' : 52,
    'VT' : 53,
    'VI' : 54,
    'VA' : 55,
    'WV' : 56,
    'WI' : 57,
    'WY' : 58
}
VAL_TO_STATES = {
    0 : 'NU',
    1 : 'AL',
    2 : 'AK',
    3 : 'AS',
    4 : 'AZ',
    5 : 'AR',
    6 : 'CA',
    7 : 'CO',
    8 : 'CT',
    9 : 'DE',
    10 : 'DC',
    11 : 'FM',
    12 : 'FL',
    13 : 'GA',
    14 : 'GU',
    15 : 'HI',
    16 : 'ID',
    17 : 'IL',
    18 : 'IN',
    19 : 'IA',
    20 : 'KS',
    21 : 'KY',
    22 : 'LA',
    23 : 'ME',
    24 : 'MH',
    25 : 'MD',
    26 : 'MA',
    27 : 'MI',
    28 : 'MN',
    29 : 'MS',
    30 : 'MO',
    31 : 'MT',
    32 : 'NE',
    33 : 'NV',
    34 : 'NH',
    35 : 'NJ',
    36 : 'NM',
    37 : 'NY',
    38 : 'NC',
    39 : 'ND',
    40 : 'MP',
    41 : 'OH',
    42 : 'OK',
    43 : 'OR',
    44 : 'PW',
    45 : 'PA',
    46 : 'PR',
    47 : 'RI',
    48 : 'SC',
    49 : 'SD',
    50 : 'TN',
    51 : 'TX',
    52 : 'UT',
    53 : 'VT',
    54 : 'VI',
    55 : 'VA',
    56 : 'WV',
    57 : 'WI',
    58 : 'WY'
}
